[build]
builder = "nixpacks"
buildCommand = "composer install && npm install && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --port=$PORT --host=0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"